//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSTeamManagement.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculateEmails
    {
        public int CalculateEmailsId { get; set; }
        public System.DateTime Date { get; set; }
        public int MailCountAdd { get; set; }
        public int MailCountSent { get; set; }
        public int MailCountProcessed { get; set; }
        public int TaskCountAdded { get; set; }
        public int TaskCountRemoved { get; set; }
        public int TaskCountFinished { get; set; }
    }
}
