//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSTeamManagement.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DictValue()
        {
            this.WorkTime = new HashSet<WorkTime>();
        }
    
        public Nullable<int> DictonaryId { get; set; }
        public int DictValueId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTime> WorkTime { get; set; }
    }
}
