//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSTeamManagement.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamFeadbackEntities : DbContext
    {
        public TeamFeadbackEntities()
            : base("name=TeamFeadbackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WorkTimeDetails> WorkTimeDetails { get; set; }
        public virtual DbSet<CalculateEmails> CalculateEmails { get; set; }
        public virtual DbSet<dbUp> dbUp { get; set; }
        public virtual DbSet<dbUp1> dbUp1 { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<DictValue> DictValue { get; set; }
        public virtual DbSet<Internal> Internal { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<WorkLunch> WorkLunch { get; set; }
        public virtual DbSet<WorkTime> WorkTime { get; set; }
        public virtual DbSet<WorkTimeComment> WorkTimeComment { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
    }
}
